apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persisten-volume 
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/local/k8s"
    type: DirectoryOrCreate
